"""Xueqiu (雪球) API client.

Fetches stock quotes, search results, hot posts, and hot stock rankings
from Xueqiu's public API.  Uses a cookie-aware urllib opener adapted from
agent-reach's channel implementation.

Cookie strategy (priority order):
    1. Saved cookie string in ~/.webmirage/config.yaml (key: xueqiu_cookie)
    2. Auto-extract from Chrome/Edge (requires browser-cookie3 + prior login)
    3. Homepage visit fallback (yields public session cookies - may 400)

The ``xq_a_token`` cookie is generated by Xueqiu's frontend JavaScript and
cannot be obtained through pure HTTP requests.  To use authenticated APIs:

    1. Open https://xueqiu.com in Chrome/Edge (log in if you have an account)
    2. Open DevTools (F12) -> Application -> Cookies -> xueqiu.com
    3. Copy all cookie pairs as "name=value; name2=value2"
    4. Add to ~/.webmirage/config.yaml:
         xueqiu_cookie: "acw_tc=xxx; xq_a_token=yyy; device_id=zzz; ..."
"""

from __future__ import annotations

import http.cookiejar
import json
import re
import urllib.parse
import urllib.request
from typing import Any

from loguru import logger

_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)
_REFERER = "https://xueqiu.com/"
_TIMEOUT = 10
_XUEQIU_HOME = "https://xueqiu.com"


class XueqiuError(Exception):
    """Base error for Xueqiu API failures."""


class XueqiuClient:
    """Cookie-aware HTTP client for Xueqiu's public API."""

    def __init__(self, cookie_str: str = "") -> None:
        self._cookie_jar = http.cookiejar.CookieJar()
        self._opener = urllib.request.build_opener(
            urllib.request.HTTPCookieProcessor(self._cookie_jar),
        )
        self._cookie_str = cookie_str
        self._initialized = False

    # ------------------------------------------------------------------ #
    # Cookie management
    # ------------------------------------------------------------------ #

    def _inject_cookie_string(self, cookie_str: str) -> None:
        """Parse a 'name=value; name2=value2' string and inject into the jar."""
        for pair in cookie_str.split(";"):
            pair = pair.strip()
            if "=" not in pair:
                continue
            name, _, value = pair.partition("=")
            cookie = http.cookiejar.Cookie(
                version=0,
                name=name.strip(),
                value=value.strip(),
                port=None,
                port_specified=False,
                domain=".xueqiu.com",
                domain_specified=True,
                domain_initial_dot=True,
                path="/",
                path_specified=True,
                secure=True,
                expires=None,
                discard=True,
                comment=None,
                comment_url=None,
                rest={},
            )
            self._cookie_jar.set_cookie(cookie)

    def _load_cookies_from_browser(self) -> bool:
        """Try to extract Xueqiu cookies from local Chrome browser.

        Requires the ``browser-cookie3`` package and that the user has
        logged in to xueqiu.com in Chrome.  Returns True on success.
        """
        try:
            import browser_cookie3
        except ImportError:
            logger.debug("browser-cookie3 not installed, skipping browser cookie extraction")
            return False

        try:
            # Try Chrome first, then Edge (common on Windows)
            for browser_fn in (
                browser_cookie3.chrome,
                browser_cookie3.edge,
            ):
                try:
                    cj = browser_fn(domain_name="xueqiu.com")
                    # Copy cookies into our jar
                    has_token = False
                    for cookie in cj:
                        self._cookie_jar.set_cookie(cookie)
                        if cookie.name == "xq_a_token":
                            has_token = True
                    if has_token:
                        logger.info("Loaded Xueqiu cookies from browser (found xq_a_token)")
                        return True
                except Exception as exc:
                    logger.debug("Browser cookie extraction failed for {}: {}", browser_fn.__name__, exc)
            logger.warning("Browser cookies found but no xq_a_token - user may not be logged in to xueqiu.com")
            return False
        except Exception as exc:
            logger.warning("Failed to extract browser cookies: {}", exc)
            return False

    def ensure_cookies(self) -> None:
        """Populate session cookies (idempotent).

        Priority:
            1. Saved cookie string from config (xueqiu_cookie in config.yaml)
            2. Auto-extract from Chrome/Edge (requires browser-cookie3 + login)
            3. Homepage visit fallback (public session only - may 400 on auth APIs)
        """
        if self._initialized:
            return

        # 1. Config file cookie string
        if self._cookie_str:
            logger.debug("Using Xueqiu cookies from config")
            self._inject_cookie_string(self._cookie_str)
            self._initialized = True
            return

        # 2. Browser auto-extraction
        if self._load_cookies_from_browser():
            self._initialized = True
            return

        # 3. Homepage fallback (public session only)
        logger.debug("Falling back to homepage visit for public session cookies")
        req = urllib.request.Request(_XUEQIU_HOME, headers={"User-Agent": _UA})
        try:
            self._opener.open(req, timeout=_TIMEOUT)
        except Exception as exc:
            logger.warning("Homepage cookie fetch failed: {}", exc)
        self._initialized = True

    def _get_json(self, url: str) -> Any:
        """Fetch *url* with Xueqiu session cookies and return parsed JSON."""
        self.ensure_cookies()
        req = urllib.request.Request(
            url, headers={"User-Agent": _UA, "Referer": _REFERER}
        )
        try:
            with self._opener.open(req, timeout=_TIMEOUT) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            if exc.code == 400:
                raise XueqiuError(
                    "Xueqiu API returned 400. The xq_a_token cookie (generated by "
                    "JavaScript) is missing. To fix:\n"
                    "  1. Open https://xueqiu.com in Chrome/Edge\n"
                    "  2. F12 -> Application -> Cookies -> xueqiu.com\n"
                    "  3. Copy all cookie pairs as 'name=value; name2=value2'\n"
                    "  4. Add to ~/.webmirage/config.yaml:\n"
                    "       xueqiu_cookie: \"acw_tc=xxx; xq_a_token=yyy; ...\""
                ) from exc
            raise

    # ------------------------------------------------------------------ #
    # Public API methods
    # ------------------------------------------------------------------ #

    def get_quote(self, symbol: str) -> dict[str, Any]:
        """Get real-time stock quote with valuation metrics.

        Args:
            symbol: Stock code, e.g. SH600519 (Shanghai), SZ000858 (Shenzhen),
                    AAPL (US), 09988 (HK).

        Returns dict with: symbol, name, current, percent, chg, high, low,
                open, last_close, volume, amount, market_capital,
                turnover_rate, pe_ttm, pe_forecast, pb, eps, timestamp.
        """
        encoded = urllib.parse.quote(symbol, safe="")
        data = self._get_json(
            f"https://stock.xueqiu.com/v5/stock/quote.json"
            f"?symbol={encoded}&extend=detail"
        )
        q = (data.get("data") or {}).get("quote") or {}
        return {
            "symbol": q.get("symbol", symbol),
            "name": q.get("name", ""),
            "current": q.get("current"),
            "percent": q.get("percent"),
            "chg": q.get("chg"),
            "high": q.get("high"),
            "low": q.get("low"),
            "open": q.get("open"),
            "last_close": q.get("last_close"),
            "volume": q.get("volume"),
            "amount": q.get("amount"),
            "market_capital": q.get("market_capital"),
            "turnover_rate": q.get("turnover_rate"),
            "pe_ttm": q.get("pe_ttm"),
            "pe_forecast": q.get("pe_forecast"),
            "pb": q.get("pb"),
            "eps": q.get("eps"),
            "timestamp": q.get("timestamp"),
        }

    def search_stock(self, query: str, limit: int = 10) -> list[dict[str, Any]]:
        """Search stocks by name or code.

        Args:
            query: Stock code or Chinese name, e.g. "茅台", "600519".
            limit: Max results (default 10).

        Returns list of dicts with: symbol, name, exchange.
        """
        data = self._get_json(
            f"https://xueqiu.com/stock/search.json"
            f"?code={urllib.parse.quote(query)}&size={limit}"
        )
        stocks = data.get("stocks") or []
        return [
            {
                "symbol": s.get("code", ""),
                "name": s.get("name", ""),
                "exchange": s.get("exchange", ""),
            }
            for s in stocks[:limit]
        ]

    def get_hot_posts(self, limit: int = 20) -> list[dict[str, Any]]:
        """Get trending posts from Xueqiu community.

        Args:
            limit: Max posts (default 20, max 50).

        Returns list of dicts with: id, title, text, author, likes, url.
        """
        if limit < 0:
            raise ValueError("limit must be non-negative")
        limit = min(limit, 50)
        if limit == 0:
            return []

        data = self._get_json(
            f"https://xueqiu.com/v4/statuses/public_timeline_by_category.json"
            f"?since_id=-1&max_id=-1&count={limit}&category=-1"
        )
        items = data.get("list") or []
        results = []
        for item in items[:limit]:
            try:
                post = (
                    json.loads(item["data"])
                    if isinstance(item.get("data"), str)
                    else {}
                )
            except (json.JSONDecodeError, KeyError):
                post = {}
            user = post.get("user") or {}
            text = _strip_html(post.get("text") or post.get("description") or "")
            target = post.get("target", "")
            results.append(
                {
                    "id": post.get("id", 0),
                    "title": post.get("title") or "",
                    "text": text[:200],
                    "author": user.get("screen_name", ""),
                    "likes": post.get("like_count", 0),
                    "url": f"https://xueqiu.com{target}" if target else "",
                }
            )
        return results

    def get_hot_stocks(
        self, limit: int = 10, stock_type: int = 10
    ) -> list[dict[str, Any]]:
        """Get hot stock rankings.

        Args:
            limit:      Max results (default 10, max 50).
            stock_type: 10=人气榜 (popularity, default), 12=关注榜 (attention).

        Returns list of dicts with: symbol, name, current, percent, rank.
        """
        data = self._get_json(
            f"https://stock.xueqiu.com/v5/stock/hot_stock/list.json"
            f"?size={limit}&type={stock_type}"
        )
        items = (data.get("data") or {}).get("items") or []
        results = []
        for idx, item in enumerate(items[:limit], 1):
            results.append(
                {
                    "symbol": item.get("code") or item.get("symbol", ""),
                    "name": item.get("name", ""),
                    "current": item.get("current"),
                    "percent": item.get("percent"),
                    "rank": idx,
                }
            )
        return results


def _strip_html(text: str) -> str:
    """Remove HTML tags and decode common entities."""
    text = re.sub(r"<[^>]+>", "", text)
    for entity, char in (("&nbsp;", " "), ("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">")):
        text = text.replace(entity, char)
    return text.strip()
